### ISSUE TITLE
Invalid object name 'dbo.nyc_taxi_yellow'

### ISSUE THREAD

**Issue by CarlaRom** [malvik01/Fabric-NYC-Taxi-Data-Project#1]
Hi @malvik01! 

Thank you very much for this fantastic Microsoft Fabric End to End Data Project, for your courses and for all the high quality content you share. I really appreciate it. 

I just wanted to comment that in [pl_pres_processing_nyctaxi](https://github.com/malvik01/fabric_nyctaxi_end_to_end_data_project/wiki/02.-Code-used-in-Pipeline:-pl_pres_processing_nyctaxi) Pipeline, specifically [in the last part](https://github.com/malvik01/Fabric-NYC-Taxi-Data-Project/wiki/02.-Code-used-in-Pipeline:-pl_pres_processing_nyctaxi#sp-loading-presentation-metadata), I had an error in the Pipeline:  _**Invalid object name 'dbo.nyc_taxi_yellow'**_. I solved it by writing _**dbo.nyctaxi_yellow**_ instead of _**dbo.nyc_taxi_yellow**_. So the code looks like this:

![image](https://github.com/user-attachments/assets/3c5dcd6f-70ff-4617-a43d-240054b87bea)

Thank you again for everything, 

Best regards!

**Comment by malvik01** [comment]
Thanks @CarlaRom, much appreciated. This has been corrected now 👍🏽
